//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.10.16 at 07:12:54 PM CEST 
//


package rebecca.e26.dialogs.xmlmatrix;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the rebecca.e26.dialogs.xmlmatrix package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: rebecca.e26.dialogs.xmlmatrix
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link XAChooseMultiSet }
     * 
     */
    public XAChooseMultiSet createXAChooseMultiSet() {
        return new XAChooseMultiSet();
    }

    /**
     * Create an instance of {@link XPassage }
     * 
     */
    public XPassage createXPassage() {
        return new XPassage();
    }

    /**
     * Create an instance of {@link XSentence }
     * 
     */
    public XSentence createXSentence() {
        return new XSentence();
    }

    /**
     * Create an instance of {@link XAString }
     * 
     */
    public XAString createXAString() {
        return new XAString();
    }

    /**
     * Create an instance of {@link XAChooseOneSet }
     * 
     */
    public XAChooseOneSet createXAChooseOneSet() {
        return new XAChooseOneSet();
    }

    /**
     * Create an instance of {@link XOption }
     * 
     */
    public XOption createXOption() {
        return new XOption();
    }

    /**
     * Create an instance of {@link XMultiAxis }
     * 
     */
    public XMultiAxis createXMultiAxis() {
        return new XMultiAxis();
    }

    /**
     * Create an instance of {@link XABoolean }
     * 
     */
    public XABoolean createXABoolean() {
        return new XABoolean();
    }

    /**
     * Create an instance of {@link XARange }
     * 
     */
    public XARange createXARange() {
        return new XARange();
    }

    /**
     * Create an instance of {@link XDEntry }
     * 
     */
    public XDEntry createXDEntry() {
        return new XDEntry();
    }

    /**
     * Create an instance of {@link XASet }
     * 
     */
    public XASet createXASet() {
        return new XASet();
    }

    /**
     * Create an instance of {@link XDOpList }
     * 
     */
    public XDOpList createXDOpList() {
        return new XDOpList();
    }

}
