//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.10.16 at 07:12:54 PM CEST 
//


package rebecca.e26.dialogs.xmlmatrix;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.*;
@XmlRootElement

/**
 * <p>Java class for XDOpList complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="XDOpList">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.example.org/rebecca.e.dialogs}xDDot">
 *       &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *         &lt;element name="Val" type="{http://www.example.org/rebecca.e.dialogs}xOption"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "XDOpList", propOrder = {
    "val"
})
public class XDOpList
    extends XDDot
{

    @XmlElement(name = "Val")
    protected List<XOption> val;

    /**
     * Gets the value of the val property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the val property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getVal().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link XOption }
     * 
     * 
     */
    public List<XOption> getVal() {
        if (val == null) {
            val = new ArrayList<XOption>();
        }
        return this.val;
    }

}
