//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.05.06 at 05:14:44 PM CEST 
//

package rebecca.e25.util.io;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.JAXBException;
import javax.xml.bind.annotation.*;

import com.sun.org.apache.xml.internal.serialize.Printer;

@XmlRootElement
/*
 * <p>Java class for Dir complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained
 * within this class.
 * 
 * <pre> &lt;complexType name="Dir"> &lt;complexContent> &lt;restriction
 * base="{http://www.w3.org/2001/XMLSchema}anyType"> &lt;sequence> &lt;element
 * name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/> &lt;element
 * name="Folder" type="{http://www.example.org/FilePackage}Dir"
 * maxOccurs="unbounded" minOccurs="0"/> &lt;element name="File"
 * type="{http://www.example.org/FilePackage}File" maxOccurs="unbounded"
 * minOccurs="0"/> &lt;/sequence> &lt;/restriction> &lt;/complexContent>
 * &lt;/complexType> </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Dir", propOrder = { "name", "folder", "file" })
public class Dir implements java.io.Serializable {

	@XmlElement(name = "Name", required = true)
	protected String name;
	@XmlElement(name = "Folder")
	protected List<Dir> folder;
	@XmlElement(name = "File")
	protected List<File> file;

	/**
	 * Gets the value of the name property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getName() {
		return name;
	}

	/**
	 * Sets the value of the name property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setName(String value) {
		this.name = value;
	}

	/**
	 * Gets the value of the folder property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the folder property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getFolder().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link Dir }
	 * 
	 * 
	 */
	public List<Dir> getFolder() {
		if (folder == null) {
			folder = new ArrayList<Dir>();
		}
		return this.folder;
	}

	/**
	 * Gets the value of the file property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the file property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getFile().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link File }
	 * 
	 * 
	 */
	public List<File> getFile() {
		if (file == null) {
			file = new ArrayList<File>();
		}
		return this.file;
	}

//	public String toString() {
////		rebecca.e.util.printer.Printer P = new rebecca.e.util.printer.Printer();
////		try {
////			P.print(0, this, this.getClass().getPackage().getName());
////		} catch (JAXBException e) {
////			// TODO Auto-generated catch block
////			e.printStackTrace();
////		}
////
////		return "";
//	}

}
