//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.08.24 at 03:07:43 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.example.org/rebecca.e27.util.io", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package rebecca.e27.util.xml.io;
